use_frameworks!

platform :ios, '11.0'

target 'DawnTransition_Example' do
  pod 'DawnTransition', :path => '../'

  pod 'DawnKit'
  
  target 'DawnTransition_Tests' do
    inherit! :search_paths

    
  end
end
