use_frameworks!

platform :ios, '10.0'

target 'AmassingExtensions_Example' do
  pod 'AmassingExtensions', :path => '../'

  target 'AmassingExtensions_Tests' do
    inherit! :search_paths

    
  end
end
