use_frameworks!

platform :ios, '10.0'

target 'LentoNetworkModule_Example' do
  pod 'LentoNetworkModule', :path => '../'

  target 'LentoNetworkModule_Tests' do
    inherit! :search_paths

    
  end
end
